### ISSUE TITLE
aimbot not working

### ISSUE THREAD

**Issue by smokeyq1** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#17]
I don't know if im doing something wrong, but the aimbot is not working or it is really really bad. please help! Thanks!

**Comment by smokeyq1** [comment]
only BHop works

**Comment by RayanAlami** [comment]
> I don't know if im doing something wrong, but the aimbot is not working or it is really really bad. please help! Thanks!

This was fixed today
