### ISSUE TITLE
Not working with new update

### ISSUE THREAD

**Issue by ImNitro** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#18]
Not sure what it is now, but the new update completely stuffed up the hack. Nothing but the bhopping works anymore and that glitches sometimes. Fix please?

**Comment by RayanAlami** [comment]
> Not sure what it is now, but the new update completely stuffed up the hack. Nothing but the bhopping works anymore and that glitches sometimes. Fix please?

This was fixed today and there are more features than ever, have fun!!!
