### ISSUE TITLE
Is this a joke? Moomoo Script

### ISSUE THREAD

**Issue by pxoss** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#2]
This isnt a krunker cheat script. The only thing related to krunker is the top userscript settings
This is a moomoo script with the userscript set to krunker domain
line 19 if (window.location.href.includes("moomoo")){
Really?

**Comment by RayanAlami** [comment]
It's supposed in the future support moomoo.io and krunker.io, and by the way, KRUNKER AND MOOMOO ARE MADE BY THE SAME DEVELOPER, THATS WHY!!!!!!!!!!!! TWO hacks in one script
