### ISSUE TITLE
If you change something, the hack disables

### ISSUE THREAD

**Issue by smokeyq1** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#20]
I found an issue. The hack works perfectly good at the start, but if you do anything with the mod menu, the hack will just no longer works except player locations

**Comment by ButterPecan0915** [comment]
Yessssss i just realized that

**Comment by ButterPecan0915** [comment]
And if u download the scriptsource, it just stays on a screen 'connecting'

**Comment by RayanAlami** [comment]
> And if u download the scriptsource, it just stays on a screen 'connecting'

Was fixed today

**Comment by RayanAlami** [comment]
> I found an issue. The hack works perfectly good at the start, but if you do anything with the mod menu, the hack will just no longer works except player locations

was fixed today

**Comment by ButterPecan0915** [comment]
Thank youuu soooo much!

**Comment by RayanAlami** [comment]
> Thank youuu soooo much!

your very welcome!

**Comment by RayanAlami** [comment]
> Thank youuu soooo much!

Just in case the hack stops working, be sure to come back to this page to see if a new one is out and if there isn't, pls be patient with me.
