### ISSUE TITLE
Fantastic new update

### ISSUE THREAD

**Issue by ImNitro** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#22]
The new update is working nearly perfectly. However, Aimbot and esp options don't really work (Kind of...). It auto adjusts based on what gun you have (to an extent), but none of the options actually work. Btw, Love your work!

**Comment by RayanAlami** [comment]
> The new update is working nearly perfectly. However, Aimbot and esp options don't really work (Kind of...). It auto adjusts based on what gun you have (to an extent), but none of the options actually work. Btw, Love your work!

Thanks, I will try my best to fix the things that you said in the next update!
Have fun!!!

**Comment by RayanAlami** [comment]
Next update will have better aimbot and other features including yours that you suggested

**Comment by RayanAlami** [comment]
have fun
