### ISSUE TITLE
Script dected

### ISSUE THREAD

**Issue by stanpope** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#28]
it says script is detected :CCC

**Comment by RayanAlami** [comment]
> it says script is detected :CCC

i know, will be fixed soon

**Comment by stanpope** [comment]
ok:D

**Comment by RayanAlami** [comment]
> ok:D


HACK NOW WORKS!!!!!!

**Comment by stanpope** [comment]
YESSSSSSSSSSs!!!!! :DDD TY BB LUV U PAPA:D<333333
