### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by oof-man-of** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#3]
This is a great aimbot but there is no settings on my display, it is a spawn in and it locks on. Can you maybe consider adding a settings space for player esp, aimbot etc.?

**Comment by RayanAlami** [comment]
Hello oof-man-of, the popup before you click play to start playing is the settings. do not quit the popup as it is the settings of the hack. Thank you and I hope u have fun!!!
