### ISSUE TITLE
PLEASE READ THIS : 'SCRIPT DETECTED'.

### ISSUE THREAD

**Issue by RayanAlami** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#30]
Ok, lately krunker has been hard to hack, because they integrated an anti-hack script which makes it even harder to hack and with krunker's new menu, options, layout and everything, the next update that works will BE AVAILABLE IN A WEEK OR TWO. I am very sorry but I have to start the script from scratch because the whole krunker has changed. If you install the script now, krunker will say 'script detected' so please be patient with me. Please give me your email so I can email you as soon as the hack is fixed. Sorry for the inconvenience.

**Comment by DarkAndDark** [comment]
Ok, Thankyou For Your Tim Please Email Me When It Is Up At XDarkAndDark@gmail.com

**Comment by RayanAlami** [comment]
> Ok, Thankyou For Your Tim Please Email Me When It Is Up At [XDarkAndDark@gmail.com](mailto:XDarkAndDark@gmail.com)

ok, i will email you once the hack works

**Comment by TheKlapCode** [comment]
Ok that's is all good, please email me when it is up, skatedudejacob@outlook.com

**Comment by RayanAlami** [comment]
> Ok that's is all good, please email me when it is up, [skatedudejacob@outlook.com](mailto:skatedudejacob@outlook.com)

ok, i will

**Comment by TheKlapCode** [comment]
Cool, thx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by naroos** [comment]
Hey! Mind sending me an email too?
@haykhihiyano@gmail.com
It would be appreaciated.

**Comment by RayanAlami** [comment]
> Hey! Mind sending me an email too?
> @[haykhihiyano@gmail.com](mailto:haykhihiyano@gmail.com)
> It would be appreciated.

ok

**Comment by ltalia452** [comment]
hey my email is liam.ray.tua.talia1@gmail.com

**Comment by RayanAlami** [comment]
> hey my email is [liam.ray.tua.talia1@gmail.com](mailto:liam.ray.tua.talia1@gmail.com) can u please send me a email 4 new update

ok

**Comment by RayanAlami** [comment]
The hack now works everybody, i have sent all the people who gave me their email a message

**Comment by RayanAlami** [comment]
> Ok, Thankyou For Your Tim Please Email Me When It Is Up At [XDarkAndDark@gmail.com](mailto:XDarkAndDark@gmail.com)

google tells me that yoru email dosen't exist. Re-write your email

**Comment by Excoerrannor** [comment]
please email me when it's up, excoerrannor@gmail.com

**Comment by sikehawk** [comment]
please email me as well my email is franklinelliot82@gmail.com or 18FEliott.BFT@lmetb.ie

**Comment by THeBOToFKrunKer** [comment]
Can U PLease email me as well my email is jpresa003@gmail.com or jpresa0001@mymail.lausd.net i prefer the first email tho thanks

**Comment by AndreTiagoRocha** [comment]
Can U PLease email me as well my email is andreatnrtiagorocha@gmail.com

**Comment by nxk55** [comment]
Please Email me as well at ndkrause25@gmail.com

**Comment by yukih521** [comment]
> Ok, lately krunker has been hard to hack, because they integrated an anti-hack script which makes it even harder to hack and with krunker's new menu, options, layout and everything, the next update that works will BE AVAILABLE IN A WEEK OR TWO. I am very sorry but I have to start the script from scratch because the whole krunker has changed. If you install the script now, krunker will say 'script detected' so please be patient with me. Please give me your email so I can email you as soon as the hack is fixed. Sorry for the inconvenience.

Pls email me @yukihara521@gmail.com

**Comment by theBestgie2000** [comment]
Ok, my email is hadibishr@gmail.com

**Comment by MrTroll60** [comment]
my email is jv08162005@gmail.com

**Comment by SrVELEZ123** [comment]
> Ok, últimamente krunker ha sido difícil de hackear, porque integraron un script anti-hack que hace que sea aún más difícil de hackear y con el nuevo menú, opciones, diseño y todo de krunker, la próxima actualización que funcione ESTARÁ DISPONIBLE EN UNA SEMANA O DOS . Lo siento mucho, pero tengo que comenzar el script desde cero porque todo el krunker ha cambiado. Si instala el script ahora, krunker dirá 'script detectado', así que tenga paciencia conmigo. Por favor, dame tu correo electrónico para que pueda enviarte un correo electrónico tan pronto como se corrija el hack. Lo siento por los inconvenientes ocasionados.

HOLA CRACK¡¡¡¡¡¡¡¡¡¡  MI CORREO ELECTRONICO PARA QUE ME INFORMES ES: xxanihilatorxx@gmail.com

**Comment by theBestgie2000** [comment]
My email is hadibishr@gmail.com
