### ISSUE TITLE
Script Detected

### ISSUE THREAD

**Issue by DarkAndDark** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#31]
Yeah I Have An Issue It Says Scripted Detected

**Comment by RayanAlami** [comment]
> Yeah I Have An Issue It Says Scripted Detected

i know, i will fix it and email you once its fixed

**Comment by RayanAlami** [comment]
> Yeah I Have An Issue It Says Scripted Detected


HACK NOW WORKS!!!!!!
