### ISSUE TITLE
zombsroyale Hack Issue

### ISSUE THREAD

**Issue by Godsmiteon** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#7]
I've had an issue with the zombsroyale hack. When I try to load the unpacked, it always says im missing the manifest file. Could I add you on discord to talk about it?

**Comment by pxoss** [comment]
This entire repo is a joke.

**Comment by RayanAlami** [comment]
Please report this in the zombsroyale hack page not here. This is the krunker hack page
