### ISSUE TITLE
Hack Menu not implementing changes

### ISSUE THREAD

**Issue by justinHic** [RayanAlami/Krunker.io-Aimbot-Wallhack-Fixed-2019#8]
When I access the hack menu and change some of the settings, it doesn't change it in the game.

**Comment by pxoss** [comment]
This repo is a joke.

**Comment by AsingleFishYT** [comment]
Having same issue as justinHic

**Comment by RayanAlami** [comment]
Ok, this will be fixed soon!

**Comment by RayanAlami** [comment]
> When I access the hack menu and change some of the settings, it doesn't change it in the game.

Ok, This will be fixed, thank you. Please be patient as krunker code is hard to bypass.

**Comment by RayanAlami** [comment]
> Having same issue as justinHic

This will be fixed, thank you for telling me

**Comment by RayanAlami** [comment]
I think the latest update fixed it

**Comment by RayanAlami** [comment]
Have fun with the latest update

**Comment by Godsmiteon** [comment]
Can you check my issue that I was having with Zombsroyale?

**Comment by KrunkerIOs** [comment]
@RayanAlami Hello Rayan, first of thanks you for making the hacks. I've encounter some problems though, the hack menu isn't showing up for me. Whenever i pressed play, the only things pop up is scrip source. However the wallhack and aimbot works perfectly fine just not the esp nor bhop menu shows up
